### ISSUE TITLE
[FEATURE] Add PCR/PCRP source list

### ISSUE THREAD

**Issue by guibranco** [guibranco/BancosBrasileiros#360]
**Is your feature request related to a problem? Please describe.**
Add the list of PCR/PCRP to the bank's lists.

**Describe the solution you'd like**
Parse the following document and extract the list of banks from PCR/PCPR
[List](https://www2.nuclea.com.br/SAP/Rela%C3%A7%C3%A3o%20de%20Clientes%20PCR.pdf)

**Tasks**
- [x] Update examples/dotnet/readme.md
- [x] Update examples/php/readme.md
- [x] Update lib
- [x] Update schemas
- [x] Update src
- [x] Update changelog.md
- [x] Update readme.md
- [x] Update readme.pt-br.md
